[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzepplin/=lib/openzepplin-contracts/contracts",
    "@forge-std/=lib/forge-std/src/"
]
ignored_error_codes = [2072, 2018, 5667]

via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
