[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzepplin/=lib/openzepplin-contracts/contracts",
    "@forge-std/=lib/forge-std/src/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
